属性表添加可多选字段，标识字段是否可多选
TencentBlueKing/bk-cmdb pull request #6554
Opened 2022-12-23 09:00 UTC by laodiu

### 优化的功能:
- 属性表中添加multiple字段，用于标识该字段是否可以多选，默认不可以多选。该值一旦设定无法修改

2022-12-27 07:24 UTC, ZQHcode commented on src/scene_server/admin_server/upgrader/y3.10.202212231817/objattrdes_ismultichoice.go
> +	updateData := mapstr.MapStr{common.BKMultipleField: false}
为什么已经前面统一加了common.BKMultipleField，这里还要把全部都改为false？

2022-12-27 07:24 UTC, ZQHcode commented on src/scene_server/admin_server/upgrader/y3.10.202212231817/objattrdes_ismultichoice.go
> +	err := db.Table(common.BKTableNameObjAttDes).AddColumn(ctx, common.BKMultipleField, false)
这里不止是组织类型，是对全部的属性都加了多选这个字段。是除了组织类型外其他字段也有多选这个操作么？是的话在前面的校验中就不只需要对组织这一个类型进行校验了吧

2022-12-27 07:35 UTC, laodiu commented on src/scene_server/admin_server/upgrader/y3.10.202212231817/objattrdes_ismultichoice.go
> +	err := db.Table(common.BKTableNameObjAttDes).AddColumn(ctx, common.BKMultipleField, false)
目前就组织这个字段前端有多选的按钮，需要校验，其他字段还没有多选按钮，不需要校验吧?比如长字符，短字符，浮点数，整型等咋校验是否可多选？

2022-12-27 07:46 UTC, laodiu commented on src/scene_server/admin_server/upgrader/y3.10.202212231817/objattrdes_ismultichoice.go
> +	updateData := mapstr.MapStr{common.BKMultipleField: false}
本地测试出现点小问题

2023-01-03 06:51 UTC, wjyfelen approved these changes

2023-01-03 07:07 UTC, wcy00000000000000 requested changes

2023-01-03 07:07 UTC, wcy00000000000000 commented on src/scene_server/admin_server/upgrader/y3.10.202212231817/objattrdes_ismultichoice.go
> +func addObjAttrDesTableColumn(ctx context.Context, db dal.RDB, conf *upgrader.Config) error {
命名可以调整一下，显示出是给属性增加了是否多选的功能

2023-01-03 07:07 UTC, wcy00000000000000 commented on src/scene_server/admin_server/upgrader/y3.10.202212231817/objattrdes_ismultichoice.go
> +	err := db.Table(common.BKTableNameObjAttDes).AddColumn(ctx, common.BKMultipleField, false)
这种要校验不可以是多选，如果设置为true了就报错

2023-01-03 07:07 UTC, wcy00000000000000 commented on src/common/definitions.go
> +	BKMultipleField = "multiple"
命名改成BKIsMultipleField吧

2023-01-03 07:07 UTC, wcy00000000000000 commented on src/common/metadata/attribute.go
>  	case bson.A:
这个也是数组类型，也要校验一下

2023-01-06 08:30 UTC, wjyfelen approved these changes

2023-01-06 09:40 UTC, ZQHcode commented on src/common/metadata/attribute.go
> +		blog.Errorf("check value type failed, rid: %s", rid)
err需要打印出来

2023-01-06 09:40 UTC, ZQHcode commented on src/common/metadata/attribute.go
> +	for _, value := range valMapArr {
这个for循环放在validTableValue函数中去处理比较符合函数名的语义吧

2023-01-06 09:40 UTC, ZQHcode commented on src/common/metadata/attribute.go
> +	if attribute.IsMultiple {
用户类型是可以存多个的，这个需要确认下是否会有影响; 其他的类型也再看下是否可以多选，有没有什么问题

2023-01-06 10:19 UTC, laodiu commented on src/common/metadata/attribute.go
> +	if attribute.IsMultiple {
这地方的校验是不是可以取消掉，这个地方前端不管ismultiple为true还是false，都可以多选，而且前端默认创建时为true，如果api接口创建时，传的是ismultiple:false, 那就是单选模式，但是在前端页面还是可以勾多选，提交时报错，这会不会很奇怪？

2023-01-31 01:03 UTC, laodiu commented on src/common/util/valid.go
> +		common.FieldTypeBool, common.FieldTypeList:
单选，产品说是历史原因，其实和枚举是一样的，没区别

2023-01-31 05:52 UTC, laodiu commented on src/scene_server/topo_server/logics/model/attribute.go
> +	if data.PropertyType == common.FieldTypeUser && !isUpdate {
从这个pr开始有单选的情况了，用户字段默认为true，可以多选，页面不可以配置，这里只确保cmdb页面新建和api接口新建用户字段时置为true即可，其他任何方式将其置为false，实际使用时，可以根据报错提示和接口文档进行更新ismultiple的值

2023-01-31 06:33 UTC, wjyfelen submitted a review, later dismissed

2023-02-03 02:36 UTC, wcy00000000000000 commented on src/common/metadata/attribute.go
> +		if len(val.([]interface{})) == 0 {
```suggestion
	switch t := val.(type) {
	case []interface{}:
		if len(t) == 0 {
```

用这个方式写吧，方便一点

2023-02-03 02:36 UTC, wcy00000000000000 commented on src/scene_server/admin_server/upgrader/y3.10.202212231817/objattrdes_ismultichoice.go
> +package y3_10_202212231817
改到今天吧

2023-02-07 03:23 UTC, ZQHcode commented on src/common/metadata/attribute.go
> +		} else if len(org) == 0 && !attribute.IsRequired {
下面直接if

2023-02-07 03:23 UTC, ZQHcode commented on src/common/metadata/attribute.go
> +			if len(org) != 1 {
同上

2023-02-07 03:23 UTC, ZQHcode commented on src/scene_server/topo_server/service/object_attribute.go
> +		if err := validateCreate(*attr, fields); err != nil {
这里没有isMultiple会报错，但是没传应该是正常行为，这里需要区分出来

2023-02-07 03:54 UTC, tencentblueking-adm commented
[![CLA assistant check](https://bk-cla.bktencent.com:443/pull/badge/not_signed)](https://bk-cla.bktencent.com:443/TencentBlueKing/bk-cmdb?pullRequest=6554) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://bk-cla.bktencent.com:443/TencentBlueKing/bk-cmdb?pullRequest=6554) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://bk-cla.bktencent.com:443/check/TencentBlueKing/bk-cmdb?pullRequest=6554) it.</sub>

2023-02-07 07:59 UTC, ZQHcode commented on src/common/metadata/attribute.go
> +		if len(org) == 0 && !attribute.IsRequired {
!attribute.IsRequired这个条件不需要

2023-02-07 07:59 UTC, ZQHcode commented on src/common/metadata/attribute.go
> +		if len(org) == 0 && !attribute.IsRequired {
!attribute.IsRequired 不需要

2023-02-08 08:13 UTC, wjyfelen approved these changes

2023-02-09 06:21 UTC, wcy00000000000000 approved these changes

2023-02-09 06:53 UTC, merged