添加表格实例数据监听
TencentBlueKing/bk-cmdb pull request #6743
Opened 2023-04-03 02:45 UTC by laodiu

### 新加的功能:
- 添加表格实例数据的监听

issues #6742

2023-04-12 08:46 UTC, wcy00000000000000 requested changes

2023-04-12 08:46 UTC, wcy00000000000000 commented on src/source_controller/cacheservice/event/flow/instance_flow.go
> +	}
用引用表来区分是源模型还是引用模型

2023-04-12 08:46 UTC, wcy00000000000000 commented on src/source_controller/cacheservice/event/flow/instance_flow.go
> +		}
用引用表来区分是源模型还是引用模型

2023-04-12 08:46 UTC, wcy00000000000000 commented on src/source_controller/cacheservice/event/flow/instance_flow.go
> +	enLen := len(es)
这个获取事件数量的方式不对，而且这个返回的enLen的逻辑并没有兼容之前外层的eventLen的逻辑

2023-04-12 08:46 UTC, wcy00000000000000 commented on src/source_controller/cacheservice/event/flow/instance_flow.go
> +	}
在前面直接判断tableObjIDMap的长度是否为0，不过放classifyEvents里之后就没有这个判断了

2023-04-12 08:46 UTC, wcy00000000000000 commented on src/source_controller/cacheservice/event/flow/instance_flow.go
> +	err := f.ccDB.Table("cc_ModelQuoteRelation").Find(queryCond).Fields([]string{"src_model",
在前面判断，建议做个缓存

2023-04-12 08:46 UTC, wcy00000000000000 commented on src/source_controller/cacheservice/event/flow/instance_flow.go
> +		blog.Warn("not exist table instance, no need to convert table instance events")
不要用warnf，不报错的就不要打日志，有问题的直接报错

2023-04-12 08:46 UTC, wcy00000000000000 commented on src/source_controller/cacheservice/event/flow/instance_flow.go
> +	quoteRelMap map[string][]string) []*types.Event {
改为根据引用实例事件map和实例事件map生成classifyEvents返回的数据
逻辑为：查询实例、聚合事件、生成返回值
删除事件也要生成事件

2023-04-12 08:46 UTC, wcy00000000000000 commented on src/source_controller/cacheservice/event/flow/instance_flow.go
> +	quoteRelMap := make(map[string][]string, 0)
改成dest->src的map

2023-04-12 08:46 UTC, wcy00000000000000 commented on src/source_controller/cacheservice/event/flow/instance_flow.go
> +	tableObjIDMap := make(map[string][]*types.Event, 0)
引用实例的map改成src->events和src->instIDs

2023-04-14 02:05 UTC, laodiu commented on src/source_controller/cacheservice/event/flow/instance_flow.go
> +	quoteRelMap map[string][]string) []*types.Event {
在classifyEvents for循环里统一处理，

2023-04-14 08:08 UTC, wcy00000000000000 requested changes

2023-04-14 08:08 UTC, wcy00000000000000 commented on src/source_controller/cacheservice/service/service.go
> +			time.Sleep(time.Minute * 10)
通过watch来缓存这个关系，10分钟一次全量同步数据不准确

2023-04-14 08:08 UTC, wcy00000000000000 commented on src/source_controller/cacheservice/service/service.go
> +			modelQuoteRel := make([]mapstr.MapStr, 0)
用metadata里定义好的结构体

2023-04-14 08:08 UTC, wcy00000000000000 commented on src/source_controller/cacheservice/service/service.go
> +			destModelObjIDs := make([]string, 0)
用一个map，下面判断的时候不要双重循环

2023-04-14 08:33 UTC, laodiu commented on src/source_controller/cacheservice/service/service.go
> +	if err := s.SetModelQuoteRelToRedis(); err != nil {
那这个放到后面优化，我录个单子

2023-04-17 08:11 UTC, wcy00000000000000 commented on src/source_controller/cacheservice/event/flow/instance_flow.go
> +	srcObjIDEventsMap := make(map[string][]*types.Event, 0)
改成inst ID->最后一个event的map

2023-04-17 08:22 UTC, wcy00000000000000 commented on src/source_controller/cacheservice/event/flow/instance_flow.go
> +			instEvent := &types.Event{
每个实例用自己的最后一个event生成事件

2023-04-17 08:22 UTC, wcy00000000000000 commented on src/source_controller/cacheservice/event/flow/instance_flow.go
> +				continue
报错

2023-04-21 02:18 UTC, wcy00000000000000 requested changes

2023-04-21 11:45 UTC, wcy00000000000000 commented on src/source_controller/cacheservice/event/flow/instance_flow.go
> +			if id == propertyID {
直接获取instIDEventMap[instID].ChangeDesc.UpdatedFields[propertyID]

2023-04-21 11:45 UTC, wcy00000000000000 commented on src/source_controller/cacheservice/event/flow/instance_flow.go
> +					continue
还是要生成一下，直接按update fields不存在来搞吧

2023-04-23 07:09 UTC, wcy00000000000000 commented on src/source_controller/cacheservice/event/flow/instance_flow.go
> +		e.ChangeDesc.UpdatedFields = instIDEventMap[instID].ChangeDesc.UpdatedFields
还是需要再调整一下

2023-04-24 07:57 UTC, ZQHcode commented on src/source_controller/cacheservice/event/flow/instance_flow.go
> +		instID := gjson.Get(string(e.DocBytes), common.GetInstIDField(objID)).Int()
直接bk_inst_id

2023-04-24 07:57 UTC, ZQHcode commented on src/source_controller/cacheservice/event/flow/instance_flow.go
> +		for k, v := range e.ChangeDesc.UpdatedFields {
这个放到上面，和前面两部分抽出来

2023-04-24 07:57 UTC, ZQHcode commented on src/source_controller/cacheservice/event/flow/instance_flow.go
> +		if _, ok := instIDEventMap[instID]; !ok {
如果不ok，就给它赋予初始化值，逻辑还是可以继续往下走

2023-04-24 07:57 UTC, ZQHcode commented on src/source_controller/cacheservice/event/flow/instance_flow.go
> +		if _, ok := instIDEventMap[instID].ChangeDesc.UpdatedFields[propertyID]; !ok {
不管有没有propertyID，可以直接覆盖

2023-04-25 08:40 UTC, ZQHcode commented on src/source_controller/cacheservice/event/flow/instance_flow.go
> +	if err != nil {
放191行

2023-04-25 08:40 UTC, ZQHcode commented on src/common/tablenames.go
> +	if len(suffixSlice) == 0 || len(suffixSlice) == 1 {
<= 1

2023-04-25 08:40 UTC, ZQHcode commented on src/source_controller/cacheservice/event/flow/instance_flow.go
> +		if len(objID) == 0 {
现在没这种情况了吧

2023-04-25 08:40 UTC, ZQHcode commented on src/source_controller/cacheservice/event/flow/instance_flow.go
> +func (f *InstanceFlow) convertToInstEvents(es map[int]*types.Event, srcObjIDInstIDsMap map[string][]int64,
同样传下rid

2023-04-25 09:09 UTC, ZQHcode approved these changes

2023-04-25 09:27 UTC, wcy00000000000000 approved these changes

2023-04-25 11:28 UTC, merged