1. 删除模块和服务模板时，自动删除模块上的主机自动应用；2. 编写upgrade，将之前删除的模块对应的自动应用规则删除
TencentBlueKing/bk-cmdb pull request #7351
Opened 2023-08-11 08:26 UTC by bd-xiaowang

### 修复的问题：
- 1. 删除模块和服务模板时，自动删除模块上的主机自动应用；
- 2. 编写upgrade，将之前删除的模块对应的自动应用规则删除

2023-08-11 08:29 UTC, wcy00000000000000 commented on src/scene_server/proc_server/service/servicetemplate.go
> +		listRuleOption := metadata.ListHostApplyRuleOption{
不用查，直接删了就可以了

2023-08-11 08:32 UTC, wcy00000000000000 commented on src/scene_server/admin_server/upgrader/y3.11.202308101200/delete_host_apply_rule.go
> +func listDirtyDataModuleIds(ctx context.Context, db dal.RDB) ([]int64, error) {
分页查，分页删

2023-08-11 08:34 UTC, wcy00000000000000 commented on src/scene_server/admin_server/upgrader/y3.11.202308101200/delete_host_apply_rule.go
> +		count, err := db.Table(common.BKTableNameBaseModule).Find(filter).Count(ctx)
不要一个个count，分页获取module ID然后代码里对比，下同

2023-08-14 07:23 UTC, ZQHcode commented on src/scene_server/admin_server/upgrader/y3.11.202308101200/delete_host_apply_rule.go
> +	moduleIdSet := make(map[int64]bool, len(moduleIds))
```suggestion
	moduleIDMap := make(map[int64]bool, len(moduleIds))
```

2023-08-14 07:23 UTC, ZQHcode commented on src/scene_server/admin_server/upgrader/y3.11.202308101200/delete_host_apply_rule.go
> +		return result, err
```suggestion
		return result, nil
```

2023-08-14 07:23 UTC, ZQHcode commented on src/scene_server/admin_server/upgrader/y3.11.202308101200/delete_host_apply_rule.go
> +			return result, err
```suggestion
			return nil, err
```

2023-08-14 07:23 UTC, ZQHcode commented on src/scene_server/admin_server/upgrader/y3.11.202308101200/delete_host_apply_rule.go
> +		ruleIdSet := make(map[int64]bool, len(ruleIds))
```suggestion
		ruleIDMap := make(map[int64]bool, len(ruleIds))
```

2023-08-14 07:23 UTC, ZQHcode commented on src/scene_server/admin_server/upgrader/y3.11.202308101200/delete_host_apply_rule.go
> +		common.HostApplyEnabledField: true,
模块为false的情况下是不开启主机属性自动应用，还可以再开启的，这个时候它关联的主机属性自动应用规则也不能删除

2023-08-14 07:23 UTC, ZQHcode commented on src/scene_server/admin_server/upgrader/y3.11.202308101200/delete_host_apply_rule.go
> +	var result []int64
和模块的代码一样，调整下

2023-08-14 07:23 UTC, ZQHcode commented on src/scene_server/proc_server/service/servicetemplate.go
> +			blog.Errorf("delete service template host apply rule failed, bizID: %d, "+
日志把error打出来

2023-08-14 07:23 UTC, ZQHcode commented on src/scene_server/topo_server/service/inst_module.go
> +			blog.Errorf("delete host apply rule failed, bizID: %d, rid: %s", bizID, ctx.Kit.Rid)
把error打出来

2023-08-14 07:23 UTC, ZQHcode commented on src/source_controller/coreservice/core/hostapplyrule/rule.go
> -	if len(option.RuleIDs) == 0 {
为什么要删除这个？这样和原逻辑不符合了

2023-08-21 02:51 UTC, wcy00000000000000 commented on src/source_controller/coreservice/core/hostapplyrule/rule.go
>  func (p *hostApplyRule) DeleteHostApplyRule(kit *rest.Kit, bizID int64,
这个函数判断一下RuleIDs、ModuleIDs、ServiceTemplateIDs中一个参数必填吧

2023-08-21 02:51 UTC, wcy00000000000000 commented on src/scene_server/admin_server/upgrader/y3.11.202308101200/pkg.go
> +		blog.Errorf("upgrade y3.11.202308101200 delete ModuleHostApplyRule failed, err: %v", err)
```suggestion
		blog.Errorf("upgrade y3.11.202308101200 delete host apply rule by module failed, err: %v", err)
```

2023-08-21 02:51 UTC, wcy00000000000000 commented on src/scene_server/admin_server/upgrader/y3.11.202308101200/pkg.go
> +		blog.Errorf("upgrade y3.11.202308101200 delete ServiceTemplateHostApplyRule failed, err: %v", err)
```suggestion
		blog.Errorf("upgrade y3.11.202308101200 delete host apply rule by service template failed, err: %v", err)
```

2023-08-21 02:51 UTC, wcy00000000000000 commented on src/scene_server/admin_server/upgrader/y3.11.202308101200/delete_host_apply_rule.go
> +func deleteModuleHostApplyRule(ctx context.Context, db dal.RDB) error {
分页方式有问题，逻辑应该是for循环里面先查一批自动应用，判断对应的模块是否存在，不存在的删除
服务模板也这样处理

2023-08-30 06:44 UTC, wcy00000000000000 commented on src/scene_server/admin_server/upgrader/y3.11.202308101200/delete_host_apply_rule.go
> +func deleteModuleHostApplyRule(ctx context.Context, db dal.RDB) error {
分页逻辑还是有问题，在分页里判断模块是否存在，不要在外面先把module ID都查出来

2023-08-30 06:44 UTC, wcy00000000000000 commented on src/source_controller/coreservice/core/hostapplyrule/rule.go
> +			err, filter, kit.Rid)
```suggestion
		blog.Errorf("delete host apply rules failed, err: %v, filter: %+v, rid: %s", err, filter, kit.Rid)
```

2023-08-31 07:04 UTC, wcy00000000000000 requested changes

2023-08-31 07:04 UTC, wcy00000000000000 commented on src/scene_server/admin_server/upgrader/y3.11.202308101200/delete_host_apply_rule.go
> +	var pageSize uint64 = 2000
改成100吧，分页目的就是不要一次性查那么多

2023-08-31 07:04 UTC, wcy00000000000000 commented on src/scene_server/admin_server/upgrader/y3.11.202308101200/delete_host_apply_rule.go
> +		for start := uint64(0); start < moduleCnt; start += pageSize {
模块不要查全量，用module ID数组查

2023-09-04 11:51 UTC, ZQHcode commented on src/common/util/array.go
> +	intMap2 := make(map[int64]bool)
用map[int64]struct

2023-09-04 11:51 UTC, ZQHcode commented on src/scene_server/admin_server/upgrader/y3.11.202308101200/delete_host_apply_rule.go
> +		modIdArr := make([]int64, 0)
```suggestion
		moduleIDs := make([]int64, 0)
```

2023-09-04 11:51 UTC, ZQHcode commented on src/scene_server/admin_server/upgrader/y3.11.202308101200/delete_host_apply_rule.go
> +		moduleIds := make([]map[string]int64, 0)
```suggestion
		dbModuleIDs := make([]map[string]int64, 0)
```

2023-09-04 11:51 UTC, ZQHcode commented on src/scene_server/admin_server/upgrader/y3.11.202308101200/delete_host_apply_rule.go
> +		serviceTemplateIds := make([]map[string]int64, 0)
dbSrvTmplIDs

2023-09-04 11:51 UTC, ZQHcode commented on src/scene_server/admin_server/upgrader/y3.11.202308101200/delete_host_apply_rule.go
> +		srvTemIdArr := make([]int64, 0)
srvTmpIDs

2023-09-04 11:55 UTC, ZQHcode commented on src/scene_server/admin_server/upgrader/y3.11.202308101200/delete_host_apply_rule.go
> +		ruleArr := make([]int64, 0)
这些都没改，还有去重逻辑

2023-09-04 13:06 UTC, ZQHcode submitted a review, later dismissed

2023-09-05 01:53 UTC, ZQHcode approved these changes

2023-09-05 03:17 UTC, wcy00000000000000 commented on src/scene_server/admin_server/upgrader/y3.11.202309050900/delete_host_apply_rule.go
> +	for startIdx := uint64(0); startIdx < ruleCnt; startIdx += pageSize {
删除的情况下用start limit分页不一定准，可以参考migrateProcBindInfo这种分页方式

2023-09-05 08:30 UTC, wcy00000000000000 commented on src/scene_server/admin_server/upgrader/y3.11.202309050900/delete_host_apply_rule.go
> +		moduleField := map[string]interface{}{
这个函数后面这一些逻辑适当加一下空行

2023-09-05 09:35 UTC, wcy00000000000000 commented on src/scene_server/admin_server/upgrader/y3.11.202309050900/delete_host_apply_rule.go
> +		sort := "-bk_module_id"
-表示从大到小排序，这里应该是从小到大排序

2023-09-05 11:38 UTC, ZQHcode approved these changes

2023-09-05 11:39 UTC, wcy00000000000000 approved these changes

2023-09-05 11:39 UTC, merged