excel导入导出重构
TencentBlueKing/bk-cmdb pull request #7353
Opened 2023-08-14 04:16 UTC by ZQHcode

### 新加的功能:
- excel操作基础库
- 生成主机模版
- 生成模型实例模版
- 导出模型实例
- 导出主机

2023-08-28 08:33 UTC, wcy00000000000000 requested changes

2023-08-28 08:33 UTC, wcy00000000000000 commented on src/web_server/service/excel/operator/inst/exporter/inst_func.go
> +		items, ok := property.Option.([]interface{})
解析枚举option用metadata.ParseEnumOption

2023-08-28 08:33 UTC, wcy00000000000000 commented on src/web_server/service/excel/operator/inst/importer/importer.go
> +	hasDoneNext := false
这个看起来没什么用

2023-08-30 03:41 UTC, ZQHcode commented on pkg/excel/excel.go
> +	filePath        string
这个是因为有个clean方法，用途是删除临时文件，用户在调用的时候，可能已经把excel给close了，此时获取不到路径

2023-08-30 03:46 UTC, ZQHcode commented on pkg/excel/excel.go
> +func OpenOrCreate() OperatorFunc {
也是一样需要判断是否要保留的

2023-08-30 03:51 UTC, ZQHcode commented on pkg/excel/excel.go
> +func (excel *Excel) deleteSheet(sheet string) error {
如果直接调用DeleteSheet，此时这个函数是有锁的；其他函数也有锁的情况下，调用子函数里面也有同一个锁，那么会死锁；所以这里把这些逻辑拆成小写非导出函数，代表包内其他函数可以直接调用，包外调不到

2023-08-30 03:52 UTC, ZQHcode commented on pkg/excel/excel.go
> +	if err := excel.writers[sheet].Flush(); err != nil {
只是单纯把数据刷到磁盘

2023-08-30 06:42 UTC, ZQHcode commented on pkg/excel/excel.go
> +		if _, err := os.Stat(dirPath); err != nil {
MkdirAll函数如何目录存在，那么是不会做任何事情的，正常返回

2023-08-30 06:48 UTC, ZQHcode commented on pkg/excel/excel.go
> +func (excel *Excel) CreateSheet(sheet string) error {
用户可能就只需要创建，而不需要进行写入；如果不创建不能创建writer

2023-08-30 06:55 UTC, ZQHcode commented on pkg/excel/excel.go
> +func (excel *Excel) mergeCell(sheet string, hCell, vCell string) error {
理由同上

2023-08-30 06:59 UTC, ZQHcode commented on pkg/excel/excel.go
> +func (excel *Excel) Close() (err error) {
writer不需要，他只有flush方法，然后在我们自己的Flush方法里也会把这个引用删掉

2023-08-30 07:00 UTC, ZQHcode commented on pkg/excel/excel.go
> +		if err = excel.file.Close(); err != nil {
返回变量里声明了err，他会把错误返回

2023-08-30 07:01 UTC, ZQHcode commented on pkg/excel/excel.go
> +func (excel *Excel) Clean() error {
操作不一样，excel生成之后，关闭流然后将文件传给用户之后，才可以调用clean删除临时文件

2023-08-30 07:04 UTC, ZQHcode commented on pkg/excel/excel.go
> +func (excel *Excel) MergeSameRowCell(sheet string, colIdx, rowIdx, length int) error {
MergeCell就是说的函数，只是它的子函数mergeCell都给大家调用而已

2023-08-30 07:15 UTC, ZQHcode commented on pkg/excel/validation.go
> +const (
都是校验使用到的常量所以放一起了，注释补充添加了

2023-08-30 07:43 UTC, ZQHcode commented on src/common/definitions.go
> +	Field = "field"
GetObjectData函数已经调整为结构体，然后查询主机和通用实例因为结构体不同所以没有调整，因为他俩是抽象为一个接口，请求值需要是mapStr才行

2023-08-30 10:12 UTC, ZQHcode commented on src/web_server/service/excel/core/topo_func.go
> +		result[len(objIDs)-1-idx] = TopoBriefMsg{ObjID: objID, Name: idNameMap[objID]}
尝试倒了下，差不多其实

2023-08-31 02:50 UTC, ZQHcode commented on src/web_server/service/excel/operator/inst/exporter/tmpl_operator.go
> +	kit          *rest.Kit
这是因为每次请求就会创建一个这个对象，所以kit放在对象里不会有问题；如果函数传递的话每个函数需要多一个参数，入参又变多了

2023-08-31 03:37 UTC, ZQHcode commented on src/scene_server/host_server/logics/import.go
> +func (lgc *Logics) AddHost(kit *rest.Kit, appID int64, moduleIDs []int64, ownerID string,
后续处理

2023-08-31 03:44 UTC, ZQHcode commented on src/web_server/service/excel/operator/inst/importer/param.go
> +	BuildParam(insts map[int]map[string]interface{}) (mapstr.MapStr, error)
实现类返回的数据不一样，需要用map

2023-08-31 03:45 UTC, ZQHcode commented on src/web_server/service/excel/operator/inst/exporter/param.go
> +	GetPropCond() (mapstr.MapStr, error)
同上

2023-08-31 03:45 UTC, ZQHcode commented on src/web_server/service/excel/operator/inst/exporter/param.go
> +	GetInstCond() (mapstr.MapStr, error)
同上

2023-08-31 03:45 UTC, ZQHcode commented on src/web_server/service/excel/operator/inst/exporter/param.go
> +	HasInstCond() bool
因为condition是在实现了接口的结构体里面，在外面其实不太好看

2023-08-31 03:49 UTC, ZQHcode commented on src/web_server/service/excel/operator/model/operator.go
> +	if !ok {
原逻辑这里有问题不影响导出的

2023-08-31 03:52 UTC, ZQHcode commented on src/web_server/service/excel/operator/inst/importer/importer.go
> +	hasDoneNext := false
因为执行reader.Next()会读取数据，所以需要这个变量保证不会还没消费当前数据就读下一行

2023-08-31 03:55 UTC, ZQHcode commented on src/web_server/service/excel/operator/inst/exporter/style.go
> +		return result, nil
这是因为现在可能只设置了背景，后面可能会设置字体等样式

2023-08-31 04:05 UTC, ZQHcode commented on src/web_server/service/excel/operator/inst/exporter/exporter.go
> +	bizName    = "biz_property_bk_biz_name"
这里是用于国际化的

2023-08-31 04:16 UTC, ZQHcode commented on pkg/excel/excel.go
> +	return !os.IsNotExist(err)
如果不是不存在的问题，那么就可以继续往下走逻辑，到时候如果确实有其他的问题，调用的地方后面也会报错

2023-09-05 07:07 UTC, wcy00000000000000 approved these changes

2023-09-05 07:08 UTC, merged