主机搜索支持“多个管控区域IP”的混合搜索
TencentBlueKing/bk-cmdb pull request #7422
Opened 2023-09-26 12:29 UTC by bd-xiaowang

### 新加的功能:
- 主机搜索支持“多个管控区域IP”的混合搜索

2023-09-27 08:31 UTC, ZQHcode commented on src/common/paraparse/host.go
> +			if err != nil {
直接返回err

2023-09-27 08:31 UTC, ZQHcode commented on src/common/paraparse/host.go
> +	if hasOperator == false {
```suggestion
	if !hasOperator {
```

2023-09-27 08:31 UTC, ZQHcode commented on src/common/paraparse/host.go
> +	if cloudIDArray, ok := cloudIDCond[common.BKDBIN].([]interface{}); ok {
这段if和下面的if两段可以直接抽个函数，不需要写两遍

2023-09-27 08:31 UTC, ZQHcode commented on src/common/paraparse/host.go
> +		if cloudID == -1 {
-1定义常量

2023-09-27 08:31 UTC, ZQHcode commented on src/common/paraparse/host.go
> +			// 在hostCond中有指定
如果不等与-1，返回最下面那个，把这里面的if都看下，层级减少了

2023-09-27 08:31 UTC, ZQHcode commented on src/common/paraparse/host.go
> +		if cloudID == -1 {
同上

2023-09-27 08:31 UTC, ZQHcode commented on src/common/paraparse/host.go
> +		if cloudID == -1 {
同上

2023-09-27 08:31 UTC, ZQHcode commented on src/common/paraparse/host.go
> +func getIPv6MapCond(flag string, cloudID int64, outputCloudIDMap map[string][]int64,
同上，另外看下是否可以和ipv4和一起，或者抽公共函数

2023-09-27 09:07 UTC, laodiu commented on src/common/paraparse/host.go
> +		if cloudID == -1 {
!= -1 直接返回， 减少if嵌套

2023-09-28 01:55 UTC, laodiu commented on src/common/paraparse/host.go
> +		return nil, nil
如果逻辑走到这里， outputCloudIDMap返回值为nil， 在getIPv4MapCond中对 outputCloudIDMap没有做nil判断，看下此处!ok是否需要返回错误

2023-10-08 03:45 UTC, bd-xiaowang commented on src/common/paraparse/host.go
> +		return nil, nil
已测试此处逻辑。
1、即使outputCloudIDMap的值为nil也不会发生报错；
2、在getIPv4MapCond方法如下代码中：
```
cloudIDArr, ok := outputCloudIDMap[common.BKDBIN]
	if ok {
		cloudIDArr = util.IntArrayUnique(cloudIDArr)
	}
```
无论outputCloudIDMap还是cloudIDArr的值为nil都不会报错，util.IntArrayUnique(cloudIDArr)会返回空切片，getIPv6MapCond、getFuzzyCond方法中也是同理

2023-10-11 13:00 UTC, ZQHcode commented on src/common/paraparse/host.go
> +			continue
同上

2023-10-11 13:00 UTC, ZQHcode commented on src/common/paraparse/host.go
> +			continue
同上

2023-10-15 15:41 UTC, bd-xiaowang commented on src/common/paraparse/host.go
> +	if cloudIDArray, ok := cloudIDCond[common.BKDBIN].([]interface{}); ok {
相同的代码已合并到addCloudIDInMap方法中

2023-10-16 12:01 UTC, ZQHcode commented on src/scene_server/host_server/service/host.go
> +		if cloudAreaCount > 50 {
这个值是否已经和产品最终确定了？

2023-10-16 12:01 UTC, ZQHcode commented on src/common/paraparse/host.go
> +func getIPv6MapCond(flag string, cloudID int64, outputCloudIDMap map[string][]int64,
ipv6和ipv4一样，加下注释例子

2023-10-16 12:05 UTC, ZQHcode commented on src/common/paraparse/host.go
> +			blog.Errorf("cloudID is invalid failed, err: %v, cloudID: %s", err, cloudIDStr)
rid

2023-10-16 12:05 UTC, ZQHcode commented on src/common/paraparse/host.go
> +			blog.Errorf("get ipv4 if embedded in ipv6 failed, err: %v, ip: %s", err, ipAddress)
rid

2023-10-17 07:59 UTC, bd-xiaowang commented on src/common/paraparse/host.go
> +{
不是。是不限制管控区域，直接查找IP为127.0.0.1的主机

2023-10-26 03:44 UTC, wcy00000000000000 requested changes

2023-10-26 03:44 UTC, wcy00000000000000 commented on src/common/paraparse/host.go
> +	NOTEXISTSIGN int = -1
建议不要用-1这种特殊值，改成直接在逻辑里解析

2023-10-26 03:44 UTC, wcy00000000000000 commented on src/common/paraparse/host.go
> +func splitIPv4Data(ipCond metadata.IPInfo, rid string) (map[int64][]string, error) {
这些ipv4、ipv6解析逻辑都统一抽一下

2023-11-01 07:11 UTC, wcy00000000000000 commented on src/common/paraparse/host.go
> +func getCloudIDCond(output map[string]interface{}) (map[string]interface{}, bool, error) {
为什么这里要重新解析一下cloud ID条件？可不可以先不拼条件，只传cloud id信息下来处理？

2023-11-01 07:11 UTC, wcy00000000000000 commented on src/common/paraparse/host.go
> +	switch flag {
每一个case里面都是很类似的重复逻辑，抽一下

2023-11-01 09:40 UTC, bd-xiaowang commented on src/common/paraparse/host.go
> +func parseIPv6Condition(ipCond metadata.IPInfo, exactOr []map[string]interface{}, output map[string]interface{},
没法封装这个，ipv4和ipv6两个是不同的字段类型，而且splitIPData已经有70行了，再封装到splitIPData里面会超长

2023-11-01 09:40 UTC, bd-xiaowang commented on src/common/paraparse/host.go
> +		if len(exactOr) == 0 {
不设置空条件去做查询，要么前端会返回所有数据，要么会返回条件错误

2023-11-01 09:40 UTC, bd-xiaowang commented on src/common/paraparse/host.go
> +		colonIndex = strings.Index(ipString, ":")
strings.SplitN分割后是数组，后面还是要取值赋值，好像也没有省下代码，这样做是有什么问题嘛

2023-11-01 09:40 UTC, bd-xiaowang commented on src/common/paraparse/host.go
> +			ipAddress := strings.Trim(ipPart, "[]")
上面的fullIPAddr如果在处理IPv4时就直接跳到下面去了，ipv6的话没有得处理到，所以分割完ipv6要再去一次"[]"

2023-11-01 09:40 UTC, bd-xiaowang commented on src/common/paraparse/host.go
> +func getCloudIDCond(output map[string]interface{}) (map[string]interface{}, bool, error) {
output里面就是拼凑好的管控区域条件，判断它存在就直接拿来用就好了，不需要拿出来再传

2023-11-01 09:40 UTC, bd-xiaowang commented on src/common/paraparse/host.go
> +func getIPCond(flag string, output map[string]interface{}, fieldAndCond FieldAndCondition) ([]map[string]interface{},
不一样，但是前置判断完还是要往下传，这样getIPCond函数的参数会不会太多了

2023-11-01 09:40 UTC, bd-xiaowang commented on src/common/paraparse/host.go
> +	switch flag {
这个没法再抽了吧，已经到设置字段和条件了，前面已经判断过IP类型了，这里还要判断么

2023-11-01 11:35 UTC, ZQHcode approved these changes

2023-11-01 11:45 UTC, merged