更新api文档
TencentBlueKing/bk-cmdb pull request #7442
Opened 2023-10-11 13:20 UTC by bd-xiaowang

### 新加的功能:
- xxxx
### 优化的功能:
- xxxx
### 修复的问题：
- xxxx

2023-10-12 06:32 UTC, tencentblueking-adm commented
[![CLA assistant check](https://bk-cla.bktencent.com:443/pull/badge/not_signed)](https://bk-cla.bktencent.com:443/TencentBlueKing/bk-cmdb?pullRequest=7442) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://bk-cla.bktencent.com:443/TencentBlueKing/bk-cmdb?pullRequest=7442) before we can accept your contribution.<br/>**4** out of **8** committers have signed the CLA.<br/><br/>:white_check_mark: breezelxp<br/>:white_check_mark: wcy00000000000000<br/>:white_check_mark: ZQHcode<br/>:white_check_mark: bd-xiaowang<br/>:x: plan-do-break-fix<br/>:x: cuishuang<br/>:x: tongtie<br/>:x: Minam0<br/><hr/>**tongtie** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://bk-cla.bktencent.com:443/check/TencentBlueKing/bk-cmdb?pullRequest=7442) it.</sub>

2023-10-16 12:26 UTC, ZQHcode commented on docs/apidoc/cc/zh_hans/create_dynamic_group.md
> +	"bk_biz_id": 3,
这个偏了吧

2023-10-16 12:26 UTC, ZQHcode commented on docs/apidoc/esb-cc/zh_hans/create_set.md
> +功能描述
我看其他文档都没有去掉###喔

2023-10-16 12:26 UTC, ZQHcode commented on docs/apidoc/esb-cc/zh_hans/create_set.md
> +        	"bk_set_desc": "test-set",
格式

2023-10-16 12:26 UTC, ZQHcode commented on docs/apidoc/esb-cc/zh_hans/create_set.md
>  #### data
sets[x] ?

2023-10-25 02:31 UTC, wcy00000000000000 requested changes

2023-10-25 02:31 UTC, wcy00000000000000 commented on docs/apidoc/cc/zh_hans/add_instance_association.md
> +| metadata           | object | 是       | meta data             |
metadata现在应该全都没了，你再对照接口实现看一下
全部接口都重新对照实现看一下参数对不对，不要只改文案

2023-11-15 07:04 UTC, closed without merging