api文档更新并补充权限点
TencentBlueKing/bk-cmdb pull request #7729
Opened 2024-01-12 07:09 UTC by bd-xiaowang

### 优化的功能:
- api文档更新并补充权限点

2024-01-16 12:16 UTC, ZQHcode submitted a review, later dismissed

2024-01-17 02:08 UTC, wcy00000000000000 requested changes
所有英文文档也要和中文文档一起改一下，包括权限等

2024-01-17 06:44 UTC, bd-xiaowang commented
> 所有英文文档也要和中文文档一起改一下，包括权限等

之前沟通是先只弄中文文档，是否先将中文文档review没问题然后合入了，再重新排期根据中文文档去完善英文文档？

2024-01-18 01:54 UTC, ZQHcode approved these changes

2024-01-18 01:55 UTC, wcy00000000000000 approved these changes

2024-01-18 01:59 UTC, merged