平台配置业务快照名称配置修改为业务ID
TencentBlueKing/bk-cmdb pull request #8156
Opened 2024-08-21 07:30 UTC by bd-xiaowang

平台配置业务快照名称配置修改为业务ID

2024-10-09 12:00 UTC, wcy00000000000000 requested changes

2024-10-09 12:00 UTC, wcy00000000000000 commented on src/scene_server/admin_server/upgrader/y3.14.202408201640/updateAdminConfigc.go
> +	if nil != err {
```suggestion
	if err != nil {
```

2024-10-09 12:00 UTC, wcy00000000000000 commented on src/scene_server/admin_server/upgrader/y3.14.202408201640/updateAdminConfigc.go
> +	if err := json.Unmarshal([]byte(platCfg[common.ConfigAdminValueField].(string)), dbCfg); err != nil {
platCfg[common.ConfigAdminValueField]不是string的话会panic，为什么一定要从interface转？直接map[string]string就行

2024-10-09 12:00 UTC, wcy00000000000000 commented on src/scene_server/admin_server/upgrader/y3.14.202408201640/updateAdminConfigc.go
> +	dbCfg.Backend.SnapshotBizID = 2
不能直接设置成2，要用SnapshotBizName查一下到底是哪个ID

2024-10-09 12:00 UTC, wcy00000000000000 commented on src/scene_server/admin_server/upgrader/y3.14.202408201640/updateAdminConfigc.go
> +	if err != nil {
日志

2024-10-10 07:19 UTC, bd-xiaowang commented on src/common/metadata/configadmin.go
>  	SnapshotBizName string `json:"snapshot_biz_name"`
已调整

2024-10-10 08:31 UTC, wcy00000000000000 commented on src/scene_server/datacollection/app/server.go
> +			blog.Warnf("search config admin failed, try count:%d, SearchConfigAdmin err: %v", i, err)
```suggestion
			blog.Warnf("search config admin failed, try count: %d, err: %v", i, err)
```
下面的也改一下

2024-10-10 08:31 UTC, wcy00000000000000 commented on src/scene_server/admin_server/upgrader/y3.14.202410100930/updateAdminConfigc.go
> +	var bizIDMap map[string]int64
用metadata里的业务结构体，不要用map了
然后前面需要判断一下如果已经有id了就直接return，有name才去db里查

2024-10-10 08:31 UTC, wcy00000000000000 commented on src/scene_server/admin_server/upgrader/y3.14.202410100930/updateAdminConfigc.go
> +	if bizIDMap == nil || bizIDMap[common.BKAppIDField] == 0 {
没有业务ID的话报错，不要改成默认的，这个表示用户填的名字是有问题的

2024-10-10 08:31 UTC, wcy00000000000000 commented on src/scene_server/admin_server/upgrader/y3.14.202410100930/updateAdminConfigc.go
> +	dbCfg := new(metadata.OldPlatformSettingConfig)
不要用old，可以在这个upgrader里定义一个两个字段都有的

2024-10-10 09:46 UTC, bd-xiaowang commented on src/scene_server/admin_server/upgrader/y3.14.202410100930/updateAdminConfigc.go
> +	if dbCfg.Backend.SnapshotBizName != "" {
已优化逻辑

2024-10-10 10:03 UTC, bd-xiaowang commented on src/scene_server/admin_server/upgrader/y3.14.202410100930/updateAdminConfigc.go
> +	var bizInfo metadata.BizBasicInfo
已调整

2024-10-10 10:08 UTC, wcy00000000000000 approved these changes

2024-10-10 11:22 UTC, merged