mongodb升级和dao层支持多租户
TencentBlueKing/bk-cmdb pull request #8238
Opened 2024-10-31 06:45 UTC by wcy00000000000000

### 优化的功能:
- mongodb升级和dao层支持多租户

2024-10-31 08:03 UTC, breezelxp requested changes

2024-10-31 08:03 UTC, breezelxp commented on src/storage/dal/mongo/local/tenant.go
> +type TenantMongoManager struct {
这里是不是忽略了一个关键的场景,master db也可以作为tenant db和newtenent db？

2024-10-31 08:03 UTC, breezelxp commented on src/storage/dal/mongo/local/txn_manager.go
> +		tenant: tenant,
如何确保这里的tenant不为空？是合法的？

2024-10-31 08:05 UTC, wcy00000000000000 commented on src/storage/dal/mongo/local/tenant.go
> +type TenantMongoManager struct {
在下面的初始化逻辑里https://github.com/TencentBlueKing/bk-cmdb/pull/8238/files#diff-d01085b681ac849fe14f5201c96f62c638758da613ccd339f4fca126d47ef923R83

2024-10-31 08:07 UTC, wcy00000000000000 commented on src/storage/dal/mongo/local/txn_manager.go
> +		tenant: tenant,
对于系统表事务tenant为空，为空的时候key不带tenant，本质上只是为了保证每个租户的key不冲突

2024-11-04 12:48 UTC, Anna-shine commented on src/common/tablenames.go
> +	}
可以去掉？

2024-11-04 12:54 UTC, Anna-shine approved these changes

2024-11-05 01:34 UTC, wcy00000000000000 commented on src/common/tablenames.go
> +func GenTenantTableName(tableName string, tenantID string) string {
放哪里没区别吧

2024-11-05 01:35 UTC, wcy00000000000000 commented on src/common/tablenames.go
> +	if !strings.Contains(tenantTableName, "_") {
系统表没租户，所以没报错

2024-11-05 01:38 UTC, wcy00000000000000 commented on src/storage/dal/mongo/local/mongo.go
> +	config.IsMaster = true
MongoConf是通用结构体，配置文件里的是master的mongo

2024-11-05 01:38 UTC, wcy00000000000000 commented on src/storage/dal/mongo/local/sharding.go
> +	newTenantCli, exists := sharding.dbClientMap[shardingConf.AddNewTenantDB]
不会为空

2024-11-05 01:39 UTC, wcy00000000000000 commented on src/storage/dal/mongo/local/sharding.go
> +	sharding.newTenantCli = newTenantCli
指定新增租户的时候写入到哪个db，现在还没有新增租户逻辑

2024-11-05 01:39 UTC, wcy00000000000000 commented on src/storage/dal/mongo/local/sharding.go
> +	go func() {
新增租户的时候会增加映射关系，要从db拉取

2024-11-05 03:04 UTC, ZQHcode approved these changes

2024-11-06 03:57 UTC, merged